# Generated by Django 5.0.14 on 2026-08-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
