# Generated by Django 5.0.14 on 2026-08-10 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_usertrip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(db_index=True, max_length=255)),
                ('days', models.PositiveIntegerField(default=1)),
                ('min_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('max_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('group_size', models.CharField(choices=[('Solo', 'Solo Backpacker'), ('Couple', 'Couple'), ('Small Group', 'Small Group (3-5)'), ('Event Squad', 'Event Squad (6+)')], default='Solo', max_length=50)),
                ('applied_travel_styles', models.JSONField(blank=True, default=list)),
                ('itinerary_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UserTrip',
        ),
    ]
