# Generated by Django 5.0.14 on 2026-08-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_aiitinerary_delete_usertrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiitinerary',
            name='max_budget',
        ),
        migrations.RemoveField(
            model_name='aiitinerary',
            name='min_budget',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='estimated_budget',
        ),
        migrations.RemoveField(
            model_name='travelpreference',
            name='budget_tier',
        ),
    ]
