# Generated by Django 5.0.14 on 2026-08-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_remove_aiitinerary_max_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiitinerary',
            name='max_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiitinerary',
            name='min_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
