# Generated by Django 5.0.14 on 2026-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_aiitinerary_max_budget_aiitinerary_min_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiitinerary',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
